version: '3'
services:
  api:
    build: .
    container_name: fastapi-app
    image: marcelo1706/fastapi-app
    environment:
      PORT: 8000
      APP_MODULE: main:app
    env_file:
      - .env
    ports:
      - 8000:8000
#     depends_on:
#       - svfe-api-firmador
#       - mariadb
#     networks:
#       - api_network

#   svfe-api-firmador:
#     image: svfe/svfe-api-firmador:v20230109
#     container_name: svfe-api-firmador
#     ports:
#     - "8113:8113"
#     volumes:
#     - "./firmador/temp:/uploads"
#     networks:
#       - api_network

#   mariadb:
#     container_name: database
#     image: mariadb:latest
#     ports:
#       - "3306:3306"
#     env_file:
#       - .env
#     volumes:
#       - ./data:/var/lib/mysql
#     networks:
#       - api_network

# networks:
#   api_network:
#     driver: bridge